name: Daily GraalVM native tests

on:
  schedule:
    # daily at 4:00 UTC
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  graalvm-native-tests:
    if: github.repository == 'open-telemetry/opentelemetry-java-instrumentation'
    uses: ./.github/workflows/reusable-native-tests.yml
    with:
      test-latest-deps: true

  workflow-notification:
    needs:
      - graalvm-native-tests
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.graalvm-native-tests.result == 'success' }}
