name: Reusable - Markdown link check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: lycheeverse/lychee-action@v2
        with:
          # remove version after next release of lychee-action
          lycheeVersion: latest
          # excluding links to pull requests and issues is done for performance
          args: >
            --include-fragments
            --exclude "^https://github.com/open-telemetry/opentelemetry-java-instrumentation/(issue|pull)/\\d+$"
            --exclude "^http://code.google.com/p/concurrentlinkedhashmap$"
            --max-retries 6
            .
